"""Centralized logging constants."""

LEVEL_INFO = "INFO"
LEVEL_WARN = "WARN"
LEVEL_ERROR = "ERROR"
LEVEL_SUCCESS = "SUCCESS"
LEVEL_DEBUG = "DEBUG"
LEVEL_METRIC = "METRIC"
LEVEL_CONFIG = "CONFIG"
LEVEL_RUN = "RUN"
LEVEL_COMMAND = "COMMAND"
LEVEL_SAVE = "SAVE"

LEVEL_ORDER = {
    LEVEL_DEBUG: 10,
    LEVEL_INFO: 20,
    LEVEL_CONFIG: 20,
    LEVEL_RUN: 20,
    LEVEL_METRIC: 20,
    LEVEL_SUCCESS: 20,
    LEVEL_SAVE: 20,
    LEVEL_COMMAND: 20,
    LEVEL_WARN: 30,
    LEVEL_ERROR: 40,
}

EMOJI_MAP = {
    LEVEL_INFO: "ℹ️",
    LEVEL_WARN: "⚠️",
    LEVEL_ERROR: "❌",
    LEVEL_SUCCESS: "✅",
    LEVEL_DEBUG: "🐞",
    LEVEL_METRIC: "📊",
    LEVEL_CONFIG: "⚙️",
    LEVEL_RUN: "🚀",
    LEVEL_COMMAND: "💻",
    LEVEL_SAVE: "💾",
}
